---
collections:
#  - name: ansible.posix
  - name: community.crypto
#  - name: community.general
  - name: azure.azcollection
  - name: infra.aap_configuration
    source: infra-aap_configuration-3.3.0.tar.gz
    type: file