---
- name: Genrate and save public key in azure cloud
  hosts: localhost  
  connection: local
  gather_facts: no
  vars:
    # Define your Azure credentials if not using environment variables or a credentials file
    # subscription_id: "<Your_Subscription_ID>"
    # client_id: "<Your_Client_ID>"
    resource_group_name: "azresourcegroup"
  tasks:
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: ~/azure_key
        type: rsa
        size: 2048
        state: present
      register: ssh_key_info

    # - name: Debug SSH key info
    #   debug:
    #     var: ssh_key_info

    - name: debug private key
      ansible.builtin.shell: cat ~/azure_key
      register: private_key_content
      no_log: yes
      
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: eastus
        
    - name: Create Azure SSH Public Key resource
      azure.azcollection.azure_rm_sshpublickey:
        resource_group: "{{ resource_group_name }}"
        name: myAzureSSHKey
        public_key: "{{ ssh_key_info.public_key }}"
        location: eastus

    - name: Set a variable to be used in a subsequent workflow job
      ansible.builtin.set_stats:
        data:
          azure_ssh_key: "{{ ssh_key_info.public_key }}"
          resource_group: "{{ resource_group_name }}"


- name: Attach credential declaratively using aap API and Collection for automation
  hosts: localhost
  gather_facts: false
  collections:
    - infra.aap_configuration

  vars:

    aap_hostname: "https://192.168.64.63"
    aap_username: "admin"
    aap_password: "primod123"
    aap_token: "h18YfbliJRcOpEVEt1GsnhfThvB6Io"
    aap_validate_certs: false

    controller_credentials:
      - name: AZ_ssh_key
        description: Credentials for Azure SSH Key
        organization: Default
        credential_type: "Machine"
        inputs:
          username: azureuser
          ssh_key_data: "{{ lookup('file', lookup('env','HOME') + '/azure_key') }}"

    controller_templates:
      - name: CIS_Reporting
        organization: Default
        credentials:
          - "AZ_ssh_key"
      - name: CIS
        organization: Default
        credentials:
          - "AZ_ssh_key" 

      - name: AWS_Infra_Hardning   
        organization: Default
        credentials:
          - "AZ_ssh_key" 
  roles:
    - infra.aap_configuration.controller_job_templates          
    - {role: infra.aap_configuration.controller_credentials, when: controller_credentials is defined}