---
- name: Genrate and save public key in azure cloud
  hosts: localhost  
  connection: local
  gather_facts: no
  tasks:
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: ~/azure_key
        type: rsa
        size: 2048
        state: present
      register: ssh_key_info

    - name: Debug SSH key info
      debug:
        var: ssh_key_info

    - name: debug private key
      ansible.builtin.shell: cat ~/azure_key
      register: private_key_content

    - name: Create resource group
      azure_rm_resourcegroup:
        name: azresourcegroup
        location: eastus
        
    - name: Create Azure SSH Public Key resource
      azure.azcollection.azure_rm_sshpublickey:
        resource_group: azresourcegroup
        name: myAzureSSHKey
        public_key: "{{ ssh_key_info.public_key }}"
        location: eastus

    - name: Set a variable to be used in a subsequent workflow job
      ansible.builtin.set_stats:
        data:
          azure_ssh_key: "{{ ssh_key_info.public_key }}"        
