---
- name: Genrate and save public key in azure cloud
  hosts: all
 # connection: local
  gather_facts: no
  tasks:
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: ~/.ssh/azure_key
        type: rsa
        size: 2048
        state: present
      register: ssh_key_info

    - name: Create resource group
      azure_rm_resourcegroup:
        name: azresourcegroup
        location: eastus
        
    - name: Create Azure SSH Public Key resource
      azure.azcollection.azure_rm_sshpublickey:
        resource_group: azresourcegroup
        name: myAzureSSHKey
        public_key: "{{ ssh_key_info.public_key }}"
        location: eastus      
